# Links for reference:
# - https://discord.com/developers/applications

discord:
  # The Discord bot's token.
  token: "BOT_TOKEN"
  channel-id: "CHANNEL_ID"
  # If the sender from Discord doesn't have a role, use this name.
  default-role: "Default"
  # Enables sending messages on Discord such as when the server starts up, shuts off, etc.
  status-messages: true
  # Send a message on Discord saying that a player joined or left the server.
  player-join-messsages: false
  # Send a message on Discord when a player dies.
  player-death-messsages: false
  # List of statuses the bots will cycle through at random times.
  status-list:
    - "Installing Arch Linux on every server"
    - "Making every developer use Neovim"
    - "Porting everything to Rust"
message:
  # How a message looks when sent from Minecraft
  minecraft: "**$user_name**: $message"
  # How a message looks when sent from Discord
  # Available placeholders:
  # - $display_name: The user's display name
  # - $handle: The user's handle (like @johndoe)
  # - $role: The user's highest role (like admin)
  # - $message: The user's message
  discord: "&8(&3Discord&8) &8[&a$role&8]  &2$display_name&7: &f$message"
