name: MineCord
version: '0.1.0-SNAPSHOT'
main: 'org.winlogon.MineCord'
api-version: 1.21
description: 'Uncomplicated Discord-Minecraft bridge for chat.'
website: 'https://github.com/walker84837/MineCord'
folia-supported: true
dependencies:
  server:
    ScalaLoader:
      load: BEFORE
      required: true
      join-classpath: true
